[workspace]
authors = ["Matt McCormick <matt@fideus.io>"]
channels = ["conda-forge"]
description = "Build and test documentation for the MyST Awesome Theme"
name = "docs"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
start-book-theme = "myst start"

[dependencies]
python = ">=3.12.5,<4"
deno = ">=2.2.6,<2.3"
mystmd = ">=1.10.1,<2"
nodejs = ">=22.13.0,<22.14"
